
name: 🚀 Deploy website on push
on: 
  push: 
    branches: 
    - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server:  ftp.sifulcrypto.com
        username: tamiz@mdtamiz.xyz
        password: Tamiz123456